### ISSUE TITLE
Problems with package dependency "sodium"

### ISSUE THREAD

**Issue by lhjohn** [ohdsi-studies/Covid19VaccineAesiDiagnostics#8]
I cannot install the "sodium" R package in our Ubuntu 16.04 environment as it requires some libraries. I checked and "sodium" is used for encryption, decryption, signatures, password hashing, etc..

Is this functionality required for the package to run? Is it possible to make a package release without "sodium"?

**Environment**
R version 4.0.2 (2020-06-22)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.6 LTS

**Comment by anthonysena** [comment]
@lhjohn - I think the changes made in #9 should resolve this issue. I'm going to re-open to allow you to confirm that it is working.

**Comment by lhjohn** [comment]
I believe your fix works, but unfortunately, in our offline environment it is currently not feasible to use renv, because the exact dependency versions need to be downloaded online. a couple other packages had the wrong version and the analysis threw an exception.

I now set `verifyDependencies = FALSE` and for the moment it is running. I will let you know how that goes. I can also provide a list with package version discrepancies.

**Comment by lhjohn** [comment]
Resolved for now, see my last comment.
